apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-deploy
  name: demo-deploy
spec:
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30007
    targetPort: 8080
  selector:
    app: demo-deploy
  type: NodePort

