apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
      nodePort: 30003
  selector:
    app: prometheus
    tier: backend
  type: NodePort
