apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: demo-vpa
 # namespace: vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: demo-deploy
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources: ["cpu"]
      minAllowed:
        cpu: "200m"
       # memory: "100Mi"
      maxAllowed:
        cpu: "500m"
       # memory: "600Mi"
